[package]
name = "nyx"
version = "0.1.0"
edition = "2021"

[dependencies]
anise = "0.5.2"
hifitime = "4.0.2"
log = "0.4.25"
nyx-space = "2.0.0"
peroxide = { version = "0.39.1", features = ["parquet"] }
pretty_env_logger = "0.5.0"
